AWSTemplateFormatVersion: 2010-09-09
Description: >
  MSP T2 Database Migration
  RDS PostgreSQL

Resources:
  MariaDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
    #Engine Options
      Engine: mariadb
      EngineVersion: 10.6
    #Templates
    #Settings
      DBInstanceIdentifier: targetdb-maria
      MasterUsername: admin
      MasterUserPassword: target1234
    #DB instance class
      DBInstanceClass: db.t3.small
    #Storage
      StorageType: gp2
      AllocatedStorage: 20
      MaxAllocatedStorage: 1000
    #Availability & durability
      MultiAZ: false
    #Connectivity
      #DBSubnetGroupName
      PubliclyAccessible: false
      #VPCSecurityGroups:
      #AvailabilityZone:
      Port: 33306
    #Database authentication 
      EnableIAMDatabaseAuthentication: false
    #Configuration
      DBName: MariaDB
      DBParameterGroupName: default.mariadb10.6
      OptionGroupName: default:mariadb-10-6
      BackupRetentionPeriod: 0
      StorageEncrypted: false
      EnablePerformanceInsights: false
      MonitoringInterval: 0
      #EnableCloudwatchLogsExports: 
      #  - mariadb
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      DeletionProtection: false
Outputs:
  InstanceId:
    Description: InstanceId of the newly created RDS Instance
    Value: !Ref MariaDB
  EndpointAddress:
    Description: The connection endpoint for the database
    Value: !GetAtt MariaDB.Endpoint.Address
  EndpointPort:
    Description: The port number on which the database accepts connections
    Value: !GetAtt MariaDB.Endpoint.Port
